#!/bin/bash

bin="$dotfiles/bin"
bin_exe="$bin/wexecute.exe"
old_bin_exe="$bin_exe.old"
exe="./bin/Release/net472/wexecute.exe"

case "$1" in
  undo )
    if [ ! -f "$bin_exe" ]; then
      err "Nothing to undo!"
      exit 2
    fi
    if [ ! -f "$old_bin_exe" ]; then
      err "Old .exe not found!"
      exit 2
    fi
    mv "$bin_exe" "$bin_exe.new"
    mv "$old_bin_exe" "$bin_exe"
    echo "${yellow}Undid";;
  build | install | * )
    ./stable.exe dotnet build -c Release
    echo "${pink}Built";;&
  move | install | * )
    if [ -f "$bin_exe" ]; then
      mv "$bin_exe" "$old_bin_exe"
    fi
    if [ ! -f "$exe" ]; then
      err "wexecute has not been built!"
      exit 2
    fi
    mv "$exe" "$bin_exe"
    echo "${cyan}Moved";;
esac
echo "${grey}Finished$reset"
