#!/bin/bash
# shellcheck disable=2154,2155,1090

shopt -s checkwinsize
shopt -s histappend
HISTSIZE=100
HISTFILESIZE=300
HISTCONTROL=ignoreboth

# info
if [[ $- == *i* ]]; then
  interactive=true
else
  interactive=false
fi
if shopt -q login_shell; then
  login=true
else
  login=false
fi
if [ "$(id -u)" = 0 ]; then
  root=true
else
  root=false
fi
if grep -q Microsoft /proc/version; then
  wsl=true
else
  wsl=false
fi
export interactive
export login
export root
export wsl
export dotfiles="$(dirname "$(realpath /etc/profile)")"
export ambient="$(realpath "$dotfiles/..")"
export wslfiles="$ambient/wsl"

run_dir() {
  for i in "$dotfiles/$1/"*.sh; do
    source "$i"
  done
  unset i
}

if [ -z $spawned ] || [ -n "$etc_environment_ran" ]; then
  run_dir login
fi

if $interactive; then
  run_dir interactive
fi

if $wsl; then
  source "$wslfiles/wslaunch"
fi

umask 000 # since I don't actually care too much about perms
